version: '3'
services:
  client:
    image: companies-poc-ui
    container_name: companies-poc-ui
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
  api:
    image: companies-poc-api
    container_name: companies-poc-api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:5000:5000'
